version: "3.9"
services:
  web:
    build: client/.
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URI=server

  server:
    build: server/.
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis
  redis:
    image: redis
    ports:
      - "6379:6379"
